#!/usr/bin/env bash
# Fetch hand-picked evaluation samples (~50 KB total). No multi-GB Zenodo archives.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEST="${ROOT}/tests/corpus/samples"
HF="https://huggingface.co/WolfpackArmy/pytorch-pickle-rce-poc/resolve/main"

mkdir -p "${DEST}/benign/raw" "${DEST}/benign/pytorch" \
         "${DEST}/malicious/raw" "${DEST}/malicious/pytorch"

echo "==> HuggingFace WolfpackArmy PoCs (published research samples)"
curl -fL -o "${DEST}/malicious/pytorch/poc_torchsave.pt"       "${HF}/poc_torchsave.pt"
curl -fL -o "${DEST}/malicious/pytorch/poc_evil_statedict.pt" "${HF}/poc_evil_statedict.pt"
curl -fL -o "${DEST}/benign/pytorch/benign_model.pt"            "${HF}/benign_model.pt"
curl -fL -o "${DEST}/benign/pytorch/benign_torchscript.pt"      "${HF}/benign_torchscript.pt"

echo "==> Canonical opcode reference vectors (public security test fixtures)"
printf '%s' $'cos\nsystem\n(S\'echo pwned\'\ntR.' > "${DEST}/malicious/raw/global_os_system.pkl"
printf '%s' $'S\'os\'\nS\'system\'\n\x93(S\'id\'\ntR.' > "${DEST}/malicious/raw/stack_global_os_system.pkl"
printf '%s' $'S\'os\'\np0\nS\'system\'\np1\ng0\ng1\n\x93(S\'id\'\ntR.' > "${DEST}/malicious/raw/stack_global_memo_indirect.pkl"

echo "==> Benign stdlib pickles (real pickle.dumps output)"
DEST="${DEST}" python3 << 'PY'
import os
import pickle
import datetime
from pathlib import Path

dest = Path(os.environ["DEST"]) / "benign/raw"
pickle.dump(datetime.datetime(2024, 6, 1, 12, 0, 0), open(dest / "datetime_protocol0.pkl", "wb"), protocol=0)
pickle.dump({"key": "value", "nums": [1, 2, 3]}, open(dest / "dict_protocol4.pkl", "wb"), protocol=4)
pickle.dump((1, "two", 3.0), open(dest / "tuple_protocol2.pkl", "wb"), protocol=2)
pickle.dump([1, 2, 3, 4], open(dest / "list_protocol4.pkl", "wb"), protocol=4)
pickle.dump(frozenset([1, 2]), open(dest / "set_protocol4.pkl", "wb"), protocol=4)
PY

echo "==> Gadget chain reference vectors (generated bytecode)"
"${ROOT}/polyglot/bin/python" "${ROOT}/scripts/generate_corpus_vectors.py" 2>/dev/null \
  || python3 "${ROOT}/scripts/generate_corpus_vectors.py"

echo ""
echo "Done. See tests/corpus/manifest.yaml"
find "${DEST}" -type f -exec ls -lh {} \;
